apiVersion: apps/v1
kind: Deployment
metadata:
  name: monapp-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: monapp
  template:
    metadata:
      labels:
        app: monapp
    spec:
      containers:
      - name: monapp
        image: monapp-nodejs 
        ports:
        - containerPort: 3000
